### ISSUE TITLE
Quickview not displaying default picture

### ISSUE THREAD

**Issue by juyemura** [Jazzercise/Amazon-Webstore#129]
Note: This is not upgrade related so we can hold off on this until further notice.

Example -- if you go to the Tops category and click Quickview for 3519 notice it shows the black top as the main picture (below) instead of the gray.  Notice how the alternate images are showing gray so they don't match.  Gray is the default color.  After you choose something for size (i.e., Large or Small) it seems to correct itself and the main and alternate images then match up. 

![image](https://cloud.githubusercontent.com/assets/5940948/6490327/3989347e-c25a-11e4-9c11-63d1003148e9.png)

**Comment by jjoshi-atmosol** [comment]
Hi Jeff,

We were unable to recreate the issue for product 3519, it looks like the black variation may be OOS: http://cl.ly/image/0D2J0o2T1b3c / http://cl.ly/image/0D2J0o2T1b3c

However, we were able to recreate this issue using a different product (1662). See notes below:

The variation “image swap” functionality is custom-built by us. However, the quick view is an Amazon native feature. That explains why there’s no communication between the two.

Since quick view is an Amazon native feature...In order to update the quick view iframe with the correct color variation we would need to modify Amazon’s code to override the selected variation or somehow modify the behavior adding an extra layer of code. If that’s even possible at all, it would probably be a very involved process.  Additionally, our code would be prone to be overwritten by Amazon if/when future upgrades occur or they change how the feature is coded.

The other option would be to create our own “quick view” custom code that communicates with our existing image variation add-on. And this option would also require a non-trivial amount of time to implement.

That being said, please let us know if this is something you'd still like us to work on.

Sincerely,

Jignesh

**Comment by juyemura** [comment]
If this is something that isn't trivial then let's not implement.  I'll close it out.
