### ISSUE TITLE
Issues with Sandbox

### ISSUE THREAD

**Issue by juyemura** [Jazzercise/Amazon-Webstore#130]
Here's what the Sandbox looks like now in Preview mode.  Was something not updated with the upgrade?

![image](https://cloud.githubusercontent.com/assets/5940948/6566178/088bc530-c674-11e4-8164-235755bff106.png)

**Comment by jjoshi-atmosol** [comment]
Hi Jeff,

Per our knowledge this has been the state its been in for a number of weeks now.  My guess is that its not been kept up with respect to any code changes since we typically work on fixes on the other two stores instead.

Also, we didn't run Upgrades on the sandbox, so if you'd like us to spend time to do that we certainly can.  

We can also go about fixing the sandbox so it's in parity with the B2B/B2C stores with respect to functionality and appearance.  Please let me know if you'd like us to do either of these.

Sincerely,

Jignesh

**Comment by juyemura** [comment]
Let's hold off on this for now.  Closing out this ticket.
