### ISSUE TITLE
Video Dimensions

### ISSUE THREAD

**Issue by juyemura** [Jazzercise/Amazon-Webstore#131]
We are considering changing the dimensions of the YouTube embedded videos so they use the full height of the container they are in.  This would essentially be a bigger, more zoomed in view to the user.  
![image](https://cloud.githubusercontent.com/assets/5940948/6566282/412ee0ba-c675-11e4-9ab1-1bbcedccb9f2.png)\

The issue is since the standard dimension is 16:9 for video.  How will we adjust to have it display in a vertical view rather than horizontal.

I've been doing some testing and if you upload a "cropped" video with the correct specs (e.g., 480x720) and change the width/height on the player to match, it will display like we want it -- more of a vertical display rather than horizontal.
![image](https://cloud.githubusercontent.com/assets/5940948/6566299/7163ee74-c675-11e4-9b84-20209527a82b.png)

My question is where would we change this in the code for the player on the Amazon side if it is a fixed width/height?  I looked quickly at some of the css files and didn't see any width or height specified for the video containers.  Does it just adjust to whatever the YouTube dimensions are?

**Comment by juyemura** [comment]
Please do not proceed with this until we give the go ahead.  We have a couple of questions to help us make a decision:
1. Do you see any issues with doing the above?  It's essentially using a non-standard YouTube size (not widescreen, not 16:9).  
2. Would this be an easy change in the code?  If not would there be any additional costs involved?  You can just give us a ballpark range.  

We're trying to decide at this point if it's worth pursuing or not.  

The goal would be to have it look like the videos on this page:
http://www.sweatybetty.com/clothes/tops/tshirts/flightbluemarl-boyfriend-tee/

**Comment by jjoshi-atmosol** [comment]
> My question is where would we change this in the code for the player on the Amazon side if it is a fixed width/height? 

The YouTube video code is generated by atmo.detail.js. Video dimensions are specified in line 353.

> Does it just adjust to whatever the YouTube dimensions are?

No, it uses the dimensions specified. If no dimensions are specified it uses native resolution.

> Do you see any issues with doing the above? It's essentially using a non-standard YouTube size (not widescreen, not 16:9).

You could upload a non-standard resolution video, however, youtube will convert it to 16:9 and add black space to the sides. Something like this: http://cl.ly/image/3J0t3c3g0b3z  Explanation from YouTube: https://support.google.com/youtube/answer/1722171?hl=en

> Would this be an easy change in the code? If not would there be any additional costs involved? You can just give us a ballpark range.

If you want to try and replicate the example you provided you have two options:

1. Use a 3rd party video plugin that supports custom resolutions.
2.	Using CSS, we can “cut out” part of the video and only show the middle section of it.

* If you want to try this route, you would be able to keep the existing videos as they are.  Ideally, videos won’t have any sort of information displayed, this is mainly because if they do, it will show a partial progress bar, partial title, etc.

* Example with controls: http://code.atmosol.com/~rcervantes/jazz-yt-test/withControls.html 

* Example without controls (recommended): http://code.atmosol.com/~rcervantes/jazz-yt-test/

**Comment by juyemura** [comment]
I have created a test page that I would like to show you as an example.  We created a video with custom dimensions (480x720) that was uploaded to YouTube.  Then in the embed code, I changed the dimensions of the YouTube player.  

Here's the result.  Notice there are no black bars on the side.
http://www.jazzercise.com/test/youtubetest.html

Would it be possible for us to accomplish this if we just change the dimensions in the Javascript?  Then on our side we would just always upload with our custom dimensions to YouTube.

**Comment by jjoshi-atmosol** [comment]
Hi Jeff,

I must apologize that we didn't think of that first!  Yes, that would solve the issue.

In that case, changing the video to the correct resolution shouldn't take too long.  You'll have to re-upload your videos in the right aspect ratio and update the custom text fields with the new YouTube ID for each product.

**Comment by jjoshi-atmosol** [comment]
Hi Jeff,

Just to confirm before we make the change...adding the code change now before the videos have been re-uploaded in the new size will mean that the existing videos will have black bars above and below in order to compensate for the "narrower" field of view.  If that is ok for you then we'll go ahead and make this change.  If not, then I'd suggest you re-upload all the videos first to YT in the new size and then we make the code change.  Your choice, please let me know.

Sincerely,

Jignesh

**Comment by juyemura** [comment]
Jignesh,

Yes, let me upload first then you guys can make the change.  FYI, we are actually going to be removing all existing videos except for one of them (which we can test with). The plan is the new catalog will have a bunch of videos in the new format.  I'll let you know when the one video is uploaded and what the part number is.

**Comment by juyemura** [comment]
Jignesh,

Video with the new (vertical) specs has been uploaded for item 3503.  You can use that for testing.  All other videos have been removed at this time. Unfortunately since we no longer have the sandbox I had to do this on production.  The specs for the actual video were set at 460 x 500.
